print("my name is niko")
print("i'm 10 years old")
print("i study in GOA")
print("i like programming")
print("i want to be programmer")
print("a")
print("b")
print("c")
print("d")
print("e")
print("f")
print("g")
print("h")
print("i")
print("j")
print("k")
print("l")
print("m")
print("n")
print("o")